---
deployment:
  tasks:
    - export DEPLOYPATH=/home/khatxoha/public_html
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH/
    - /bin/cp index.php $DEPLOYPATH/
    - /bin/chmod -R 755 $DEPLOYPATH/storage
    - /bin/chmod -R 755 $DEPLOYPATH/bootstrap/cache
